[versions]
appcompat = "1.7.0"
material = "1.12.0"
activity = "1.7.2"
constraintlayout = "2.1.4"
junit = "4.13.2"
ext-junit = "1.1.5"
espresso = "3.6.1"

[plugins]
android-application = { id = "com.android.application", version = "8.5.0" }
android-library = { id = "com.android.library", version = "8.5.0" }

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version = "1.7.0" }
material = { group = "com.google.android.material", name = "material", version = "1.12.0" }
activity = { group = "androidx.activity", name = "activity-ktx", version = "1.7.2" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version = "2.1.4" }
junit = { group = "junit", name = "junit", version = "4.13.2" }
ext-junit = { group = "androidx.test.ext", name = "junit", version = "1.1.5" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version = "3.6.1" }

